export interface Vehicle {
  id: string;
  slug: string;
  title: string;
  make: string;
  model: string;
  year: number;
  price_kes: number;
  rental_price_daily?: number;
  type: "sedan" | "suv" | "motorbike" | "truck" | string;
  condition: "new" | "used";
  mileage: number;
  fuel_type: string;
  transmission: string;
  images: string[];
  is_verified?: boolean;
  is_iom_stock?: boolean;
  is_featured?: boolean;
}

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "1",
    slug: "porsche-911-carrera",
    title: "Carrera 911 Performance",
    make: "Porsche",
    model: "911 Carrera",
    year: 2024,
    price_kes: 24500000,
    rental_price_daily: 120000,
    type: "sedan",
    condition: "new",
    mileage: 0,
    fuel_type: "Petrol",
    transmission: "PDK Automatic",
    images: ["/images/porsche-911.jpg"],
    is_verified: true,
    is_iom_stock: true,
    is_featured: true,
  },
  {
    id: "2",
    slug: "mercedes-g63-amg",
    title: "G63 AMG Edition",
    make: "Mercedes-Benz",
    model: "G63 AMG",
    year: 2023,
    price_kes: 38000000,
    rental_price_daily: 150000,
    type: "suv",
    condition: "used",
    mileage: 12400,
    fuel_type: "Petrol",
    transmission: "AMG Speedshift",
    images: ["/images/mercedes-g63.jpg"],
    is_verified: true,
    is_iom_stock: true,
    is_featured: true,
  },
  {
    id: "3",
    slug: "bentley-continental-gt",
    title: "Continental GT Azure",
    make: "Bentley",
    model: "Continental GT",
    year: 2024,
    price_kes: 42000000,
    type: "sedan",
    condition: "new",
    mileage: 0,
    fuel_type: "Petrol",
    transmission: "8-Speed Dual Clutch",
    images: ["/images/bentley-continental.jpg"],
    is_verified: true,
    is_iom_stock: true,
  },
  {
    id: "4",
    slug: "ducati-panigale-v4",
    title: "Panigale V4 Superbike",
    make: "Ducati",
    model: "Panigale V4",
    year: 2024,
    price_kes: 4500000,
    rental_price_daily: 25000,
    type: "motorbike",
    condition: "new",
    mileage: 0,
    fuel_type: "Petrol",
    transmission: "Manual 6-Speed",
    images: ["/images/ducati-panigale.jpg"],
    is_verified: true,
    is_iom_stock: true,
  },
  {
    id: "5",
    slug: "range-rover-autobiography",
    title: "Autobiography Luxury",
    make: "Land Rover",
    model: "Range Rover",
    year: 2023,
    price_kes: 32000000,
    type: "suv",
    condition: "used",
    mileage: 8200,
    fuel_type: "Diesel",
    transmission: "Automatic",
    images: ["/images/rangerover sport.jpg"],
    is_verified: true,
  },
  {
    id: "6",
    slug: "scania-r500-heavy",
    title: "Scania R500 V8 Heavy",
    make: "Scania",
    model: "R500",
    year: 2022,
    price_kes: 15500000,
    type: "truck",
    condition: "used",
    mileage: 45000,
    fuel_type: "Diesel",
    transmission: "Opticruise",
    images: ["/images/scania-r500.jpg"],
    is_verified: true,
  },
  {
     id: "7",
     slug: "luxury-sedan-merc-s-class",
     title: "S-Class Elite Diplomat",
     make: "Mercedes-Benz",
     model: "S580",
     year: 2024,
     price_kes: 28500000,
     type: "sedan",
     condition: "new",
     mileage: 0,
     fuel_type: "Petrol",
     transmission: "9G-TRONIC",
     images: ["/images/mercedes-s-class.jpg"],
     is_verified: true,
  },
  {
     id: "8",
     slug: "suv-bmw-x7",
     title: "X7 M-Performance",
     make: "BMW",
     model: "X7",
     year: 2023,
     price_kes: 21000000,
     type: "suv",
     condition: "new",
     mileage: 0,
     fuel_type: "Petrol",
     transmission: "Steptronic",
     images: ["/images/bmw-x7.jpg"],
     is_verified: true,
  },

  {
     id: "10",
     slug: "bike-kawasaki-h2r",
     title: "Ninja H2R Absolute",
     make: "Kawasaki",
     model: "Ninja H2R",
     year: 2024,
     price_kes: 6500000,
     type: "motorbike",
     condition: "new",
     mileage: 0,
     fuel_type: "Petrol",
     transmission: "Manual 6-Speed",
     images: ["/images/kawasaki-ninja.jpg"],
     is_verified: true,
  },
  {
     id: "11",
     slug: "sedan-audi-rs7",
     title: "RS7 Sportback Quatro",
     make: "Audi",
     model: "RS7",
     year: 2024,
     price_kes: 22500000,
     type: "sedan",
     condition: "new",
     mileage: 0,
     fuel_type: "Petrol",
     transmission: "Tiptronic",
     images: ["/images/audi-rs7.jpg"],
     is_verified: true,
  },
  {
     id: "12",
     slug: "suv-audi-q8",
     title: "Q8 Prestige Black",
     make: "Audi",
     model: "Q8",
     year: 2023,
     price_kes: 18500000,
     type: "suv",
     condition: "used",
     mileage: 5000,
     fuel_type: "Petrol",
     transmission: "Automatic",
     images: ["/images/audi-q8.jpg"],
     is_verified: true,
  }
];
